@echo off
REM Femas HR Installation Script for Windows
REM This script will:
REM 1. Prompt for Femas credentials
REM 2. Prompt for check-in and checkout times
REM 3. Create .env file
REM 4. Register tasks in Windows Task Scheduler

echo ========================================
echo   Femas HR Auto Check-in/out Installer
echo ========================================
echo.

REM ---- Check if running as Administrator ----
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo [ERROR] Please run this batch file as Administrator
    echo.
    echo Right-click this file and select "Run as Administrator"
    echo.
    pause
    exit /b 1
)

SET SCRIPT_DIR=%~dp0
SET ENV_FILE=%SCRIPT_DIR%.env

echo [Step 1/8] Configure Femas Credentials
echo ========================================
echo.

REM ---- Prompt for username ----
set /p FEMAS_USER="Enter Femas username: "
if "%FEMAS_USER%"=="" (
    echo [ERROR] Username cannot be empty
    pause
    exit /b 1
)

REM ---- Prompt for password ----
set /p FEMAS_PASS="Enter Femas password: "
if "%FEMAS_PASS%"=="" (
    echo [ERROR] Password cannot be empty
    pause
    exit /b 1
)

echo.
echo [Step 2/8] Configure Check-in/out Times
echo ========================================
echo.

REM ---- Prompt for check-in time ----
set /p CHECKIN_TIME="Enter check-in time (Format: HH:MM, e.g., 08:50): "
if "%CHECKIN_TIME%"=="" set CHECKIN_TIME=08:50
echo Check-in time set to: %CHECKIN_TIME%
echo.

REM ---- Calculate suggested checkout time (9.5 hours after check-in) ----
for /f "tokens=1,2 delims=:" %%a in ("%CHECKIN_TIME%") do (
    set CHECKIN_HOUR=%%a
    set CHECKIN_MIN=%%b
)

REM Remove leading zeros
set /a CHECKIN_HOUR=10%CHECKIN_HOUR% %% 100
set /a CHECKIN_MIN=10%CHECKIN_MIN% %% 100

REM Convert to total minutes
set /a TOTAL_MIN=CHECKIN_HOUR*60+CHECKIN_MIN

REM Add 9.5 hours (570 minutes)
set /a TOTAL_MIN=TOTAL_MIN+570

REM Convert back to hours and minutes
set /a SUGGESTED_HOUR=TOTAL_MIN/60
set /a SUGGESTED_MIN=TOTAL_MIN%%60

REM Handle day overflow (if hour >= 24)
if %SUGGESTED_HOUR% GEQ 24 set /a SUGGESTED_HOUR=SUGGESTED_HOUR-24

REM Format with leading zeros
if %SUGGESTED_HOUR% LSS 10 (set SUGGESTED_HOUR=0%SUGGESTED_HOUR%)
if %SUGGESTED_MIN% LSS 10 (set SUGGESTED_MIN=0%SUGGESTED_MIN%)

set SUGGESTED_CHECKOUT=%SUGGESTED_HOUR%:%SUGGESTED_MIN%

REM ---- Prompt for checkout time with suggestion ----
echo Suggested check-out time (9.5 hours after check-in): %SUGGESTED_CHECKOUT%
set /p CHECKOUT_TIME="Enter check-out time (or press Enter for %SUGGESTED_CHECKOUT%): "
if "%CHECKOUT_TIME%"=="" set CHECKOUT_TIME=%SUGGESTED_CHECKOUT%
echo Check-out time set to: %CHECKOUT_TIME%
echo.

REM ---- Create .env file ----
echo [Step 3/8] Creating configuration file (.env)
echo ========================================
echo.

(
echo # Femas Cloud Credentials Configuration
echo # This file is auto-generated by install.bat
echo # IMPORTANT: Never commit .env to git!
echo.
echo FEMAS_USER="%FEMAS_USER%"
echo FEMAS_PASS="%FEMAS_PASS%"
) > "%ENV_FILE%"

if exist "%ENV_FILE%" (
    echo [SUCCESS] .env file created at: %ENV_FILE%
) else (
    echo [ERROR] Failed to create .env file
    pause
    exit /b 1
)

echo.
echo [Step 4/8] Creating holidays configuration file
echo ========================================
echo.

SET HOLIDAYS_FILE=%SCRIPT_DIR%holidays
SET HOLIDAYS_EXAMPLE=%SCRIPT_DIR%holidays.example

REM ---- Copy holidays.example to holidays if it doesn't exist ----
if not exist "%HOLIDAYS_FILE%" (
    if exist "%HOLIDAYS_EXAMPLE%" (
        copy "%HOLIDAYS_EXAMPLE%" "%HOLIDAYS_FILE%" >nul
        echo [SUCCESS] holidays file created from holidays.example
        echo.
        echo You can customize the holidays file to add or remove holidays.
        echo The file supports:
        echo   - Single dates: 2025-01-01
        echo   - Date ranges:  2025-01-01~2025-01-04
        echo.
    ) else (
        echo [WARNING] holidays.example not found, skipping holidays configuration
        echo Holiday checking will only work for weekends
    )
) else (
    echo [INFO] holidays file already exists, keeping your existing configuration
)

echo.
echo [Step 5/8] Running essential tests
echo ========================================
echo.

REM ---- Test 1: Check bash installation ----
echo [Test 1/2] Checking bash installation...
where bash >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    echo [PASS] Bash is available
    if exist "%SCRIPT_DIR%test_bash.sh" (
        bash "%SCRIPT_DIR%test_bash.sh"
        if %ERRORLEVEL% NEQ 0 (
            echo [WARNING] Bash test failed, but continuing...
        )
    )
) else (
    echo [FAIL] Bash not found! Please install Git for Windows or WSL.
    echo       Download Git: https://git-scm.com/download/win
    pause
    exit /b 1
)
echo.

REM ---- Test 2: Instant checkout sanity test ----
echo [Test 2/2] Testing checkout script (instant, no delay)...
echo.

if exist "%SCRIPT_DIR%test_instant_checkout.sh" (
    bash "%SCRIPT_DIR%test_instant_checkout.sh"
    set CHECKOUT_RESULT=%ERRORLEVEL%
) else (
    echo [WARNING] test_instant_checkout.sh not found, skipping test
    set CHECKOUT_RESULT=0
)

if %CHECKOUT_RESULT% NEQ 0 (
    echo.
    set /p CONTINUE="Continue with installation? (Y/N): "
    if /i not "%CONTINUE%"=="Y" (
        echo Installation cancelled by user.
        pause
        exit /b 1
    )
)
echo.

echo.
echo [Step 6/8] Registering check-in task to Task Scheduler
echo ========================================
echo.

REM ---- Register check-in task ----
schtasks /Create /TN "FemasHR Check-in" /TR "\"%SCRIPT_DIR%checkin.bat\"" /SC DAILY /ST %CHECKIN_TIME% /F >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    echo [SUCCESS] Check-in task registered
    echo   - Task Name: FemasHR Check-in
    echo   - Run Time: %CHECKIN_TIME% (Daily)
    echo   - Execute: %SCRIPT_DIR%checkin.bat
) else (
    echo [ERROR] Check-in task registration failed
)

echo.
echo [Step 7/8] Registering check-out task to Task Scheduler
echo ========================================
echo.

REM ---- Register checkout task ----
schtasks /Create /TN "FemasHR Check-out" /TR "\"%SCRIPT_DIR%checkout.bat\"" /SC DAILY /ST %CHECKOUT_TIME% /F >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    echo [SUCCESS] Check-out task registered
    echo   - Task Name: FemasHR Check-out
    echo   - Run Time: %CHECKOUT_TIME% (Daily)
    echo   - Execute: %SCRIPT_DIR%checkout.bat
) else (
    echo [ERROR] Check-out task registration failed
)

echo.
echo [Step 8/8] Installation Complete!
echo ========================================
echo.
echo ========================================
echo     Installation Complete!
echo ========================================
echo.
echo [Configuration Summary]
echo.
echo Username: %FEMAS_USER%
echo Check-in time: %CHECKIN_TIME% (Daily)
echo Check-out time: %CHECKOUT_TIME% (Daily)
echo.
echo [Important Notes]
echo.
echo 1. Weekends and Taiwan national holidays will be skipped automatically
echo.
echo 2. View tasks in Task Scheduler:
echo    Start -^> Search "Task Scheduler"
echo.
echo 3. View logs:
echo    %%TEMP%%\femas_checkin.log
echo    %%TEMP%%\femas_checkout.log
echo.
echo 4. Manual test:
echo    checkin.bat  (Check-in)
echo    checkout.bat (Check-out)
echo.
echo 5. Uninstall:
echo    Run: uninstall.bat
echo.
pause
